---
title: Gold PR
url: http://www.goldpr.com/
repo: http://www.github.com/acidjazz/goldpr
description: We help companies grow
keywords: womens beauty pr, womens health pr, social media
image: img/share.jpg
