---
title: 'Gold PR : Top Public Relations Firm + Digital Agency'
url: https://www.goldpr.com/
repo: http://www.github.com/acidjazz/goldpr
description: Award winning public relations and digital agency. GOLD PR is a California based PR firm trusted by some of the largest brands across the globe.
keywords: womens beauty pr, womens health pr, social media
image: img/share.jpg
fb_appid: 238066406669012
