---
title: 'Gold PR : Award Winning + Top Global Public Relations Firm'
url: http://www.goldpr.com/
repo: http://www.github.com/acidjazz/goldpr
description: Award winning public relations agency. Gold PR is a California based PR firm trusted by the some of the largest brands across the globe.
keywords: womens beauty pr, womens health pr, social media
image: img/share.jpg
